[project]
name = "dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "numpy==1.26.3",
    "pandas==2.2.1",
    "streamlit==1.45.0",
]
